-- Shared read model: every source and event type lands here.
CREATE TABLE ingested_record (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    namespace_key VARCHAR(64)  NOT NULL,
    source_key    VARCHAR(32)  NOT NULL,
    event_type    VARCHAR(128) NOT NULL,
    dedup_key     VARCHAR(256) NOT NULL,
    -- Unbounded VARCHAR (= TEXT on PostgreSQL); keeps H2 PostgreSQL-mode tests
    -- and Hibernate schema validation happy on both databases.
    payload       VARCHAR      NOT NULL,
    occurred_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    ingested_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_record_source_dedup UNIQUE (source_key, dedup_key)
);

-- Reads are always scoped to a single namespace (no cross-namespace queries).
CREATE INDEX idx_record_namespace_occurred ON ingested_record (namespace_key, occurred_at DESC);

-- Worker-only dedup ledger. ledger_key = source_key + ":" + dedup_key.
CREATE TABLE ingest_ledger (
    ledger_key    VARCHAR(320) PRIMARY KEY,
    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL
);
